pipeline {
    agent any

    environment {
        IMAGE_NAME = "lab3-python-image"
    }

    stages {

        stage('Checkout') {
            steps {
              script {
            checkout([
                $class: 'GitSCM',
                branches: [[name: '*/main']],
                userRemoteConfigs: [[url: 'https://github.com/chinkurita/Jenkins-with-chatgpt-public.git']],
                extensions: [
                    [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [
                        [path: 'project3']
                    ]]
                ]
            ])
        }
            }
        }

        stage('Build Docker Image') {
            steps 
	    {
	    dir('project3'){
                sh 'docker build -t ${IMAGE_NAME}:latest .'
		}
            }
        }

        stage('Run Container for Test') {
            steps {
	    dir('project3'){
                sh 'docker run --rm ${IMAGE_NAME}:latest'
		}
            }
        }

        stage('Tag Docker Image') {
            steps {
	    dir('project3'){
                sh 'docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:v1'
		}
            }
        }

        stage('Cleanup Unused Containers') {
            steps {
                sh '''
                echo "Cleaning up"
                docker container prune -f || true
                '''
            }
        }
    }

    post {
        success {
            echo "Lab 3 Completed Successfully!"
        }
    }
}

