pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/chinkurita/Jenkins-with-chatgpt-public.git'
            }
        }

        stage('Run Script') {
            steps {
	    	dir('sample-pipeline'){
                 sh 'chmod +x app.sh'
                 sh './app.sh'
		}
            }
        }

        stage('Archive Artifact') {
            steps {
                sh 'echo "Build completed at $(date)" > build-info.txt'
                archiveArtifacts artifacts: 'build-info.txt', fingerprint: true
            }
        }
    }
}
