pipeline {
    agent {
        docker {
            image 'python:3.9'
            args '-u root'
        }
    }

    stages {
        stage('Checkout Code') {
            steps {
               git branch:'main', url:'https://github.com/chinkurita/Jenkins-with-chatgpt-public.git'
            }
        }

        stage('Run Python Command') {
            steps {
                sh 'python --version'
            }
        }

        stage('List Directory') {
            steps {
                sh 'ls -la'
            }
        }
    }
}

